site/src/main/java/ru/dom24x7/model/post/Post.java
package ru.dom24x7.model.post;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import ru.dom24x7.model.Model;
import ru.dom24x7.model.photo.Photo;
import ru.dom24x7.model.photo.dao.PhotoDAOImpl;
import ru.dom24x7.model.user.User;
import ru.dom24x7.utils.Translit;

/**
 * Пост
 * 
 * @author Евгажуков Т.Х.
 *
 */
public class Post extends Model {

	private Date createDt;
	private Date publishedDt;
	private User author;
	private String title;
	private String text;
	private int views;
	private Category category;
	private String source;
	private List<Photo> photos;

	public Post() {

		super();
	}

	public Post(int id) {

		super(id);
	}

	public Post(int id, String title) {

		super(id);
		this.title = title;
	}

	public Date getCreateDt() {

		return createDt;
	}

	public void setCreateDt(Date createDt) {

		this.createDt = createDt;
	}

	public Date getPublishedDt() {

		return publishedDt;
	}

	public void setPublishedDt(Date publishedDt) {

		this.publishedDt = publishedDt;
	}

	public User getAuthor() {

		return author;
	}

	public void setAuthor(User author) {

		this.author = author;
	}

	public String getTitle() {

		return title;
	}

	public void setTitle(String title) {

		this.title = title;
	}

	public String getText() {

		return text;
	}

	public void setText(String text) {

		this.text = text;
	}

	public int getViews() {

		return views;
	}

	public void setViews(int views) {

		this.views = views;
	}

	public Category getCategory() {

		return category;
	}

	public void setCategory(Category category) {

		this.category = category;
	}

	public String getSource() {

		return source;
	}

	public void setSource(String source) {

		this.source = source;
	}

	public List<Photo> getPhotos() {

		if (photos == null) {
			loadPhotos();
		}

		return photos;
	}

	public void loadPhotos() {

		loadPhotos(false);
	}

	public void loadPhotos(boolean full) {

		photos = new PhotoDAOImpl().list(this, full);
		if (photos == null) {
			photos = new ArrayList<Photo>();
		}
	}

	public String getShowTitle() {

		if (title != null) {
			return title;
		} else {
			if (text != null) {
				return text.substring(0, (text.length() < 200 ? text.length() : 200)) + (text.length() < 200 ? "" : "...");
			} else {
				return "";
			}
		}
	}

	public String getTranslitUrl() {

		return Translit.translitUrl(getShowTitle());
	}

	@Override
	public String toString() {

		return getShowTitle();
	}
}

site/src/main/java/ru/dom24x7/site/BaseController.java
package ru.dom24x7.site;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.ModelMap;
import ru.dom24x7.component.OpenGraph;
import ru.dom24x7.model.address.Address;
import ru.dom24x7.model.address.dao.AddressDAOImpl;
import ru.dom24x7.model.user.User;
import ru.dom24x7.security.Message;
import ru.dom24x7.security.Security;

import javax.servlet.ServletContext;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Created by timur on 22.09.16.
 *
 * Базовый класс для всех контроллеров
 */
public class BaseController {

    @Autowired
    protected ServletContext servletContext;

    @Autowired
    protected Security security;

    private static final String DESCRIPTION = "";
    private static final String KEYWORDS = "";

    protected List<Message> messages = new ArrayList<Message>();

    // сообщения об ошибках
    protected static HashMap<String, Message> ERROR_MESSAGES;

    {
        ERROR_MESSAGES = new HashMap<String, Message>();
        ERROR_MESSAGES.put("ERROR_00", new Message("Данный функционал находится в разработке", Message.TYPE_WARNING));
        ERROR_MESSAGES.put("ERROR_01", new Message("Ошибка доступа к сервису. Необходима авторизация.", Message.TYPE_ERROR));
        ERROR_MESSAGES.put("ERROR_02", new Message("Ошибка доступа к сервису. Нет прав по указанному адресу.", Message.TYPE_ERROR));
        ERROR_MESSAGES.put("ERROR_03", new Message("Ошибка доступа к сервису. Нет прав на указанный счетчик.", Message.TYPE_ERROR));
        ERROR_MESSAGES.put("ERROR_04", new Message("Ошибка доступа к сервису. Нет прав на указанное показание счетчика.", Message.TYPE_ERROR));
    }

    protected List<Address> userAddresses;

    protected void setModelMap(ModelMap model, String title) {

        setModelMap(model, title, null);
    }

    protected void setModelMap(ModelMap model, String title, String active) {

        setModelMap(model, title, DESCRIPTION, KEYWORDS, active);
    }

    protected void setModelMap(ModelMap model, String title, String description, String keywords, String active) {

        OpenGraph og = new OpenGraph();
        og.setTitle(title).setDescription(description);

        setModelMap(model, og, keywords, active);
    }

    protected void setModelMap(ModelMap model, OpenGraph og, String keywords, String active) {

        model.addAttribute("title", og.getTitle());
        model.addAttribute("description", og.getDescription());
        model.addAttribute("keywords", keywords);
        model.addAttribute("og", og);
        model.addAttribute("active", active);
        model.addAttribute("security", security);

        if (security.isAuth()) {
            User user = security.getUser();
            if (!user.isConfirmed()) {
                Message msg = new Message(null, "Необходимо подтвердить адрес электронной почты",
                        Message.TYPE_WARNING, Message.LABEL_WARN, "/profile");
                security.getNotifications().add(msg);
            }
            userAddresses = new AddressDAOImpl().list(security.getUser());
            model.addAttribute("userAddresses", userAddresses);
        }
    }
}

site/src/main/java/ru/dom24x7/site/BlogController.java
package ru.dom24x7.site;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import ru.dom24x7.cache.Categories;
import ru.dom24x7.component.OpenGraph;
import ru.dom24x7.model.photo.Photo;
import ru.dom24x7.model.photo.dao.PhotoDAOImpl;
import ru.dom24x7.model.post.Category;
import ru.dom24x7.model.post.Post;
import ru.dom24x7.model.post.dao.PostDAOImpl;
import ru.dom24x7.utils.StrUtils;

import java.util.List;

/**
 * Created by timur on 15.02.17.
 *
 * Контроллер для работы блога
 */
@Controller
public class BlogController extends BaseController {

    private static final String ACTIVE = "blog";

    @RequestMapping("/blog")
    public String indexAction(ModelMap model) {

        setModelMap(model, "Блог", ACTIVE);

        return "blog/index";
    }

    @RequestMapping("/blog/{categoryUrl}")
    public String categoryAction(@PathVariable String categoryUrl, ModelMap model) {

        Category category = Categories.getInstance().get(categoryUrl);
        if (category == null) {
            return "redirect:/blog";
        }

        setModelMap(model, "Блог. Посты категории: " + category.getName(), ACTIVE);
        model.addAttribute("category", category);

        return "blog/index";
    }

    @RequestMapping("/blog/post/{postId}/{translit}")
    public String postAction(@PathVariable int postId, @PathVariable String translit, ModelMap model) {

        Post post = new PostDAOImpl().get(postId);
        if (post == null) {
            return "redirect:/blog";
        }

        List<Post> postsForNav = new PostDAOImpl().listForNav();

        OpenGraph og = new OpenGraph();
        og.setTitle(post.getShowTitle());
        og.setDescription(StrUtils.isEmpty(post.getText()) ? post.getShowTitle() : post.getText().split("<hr>")[0].replaceAll("\\<[^>]*>",""));
        og.setType(OpenGraph.OG_TYPE_ARTICLE);
        og.setUrl(TechController.URL + "/blog/post/" + postId + "/" + translit);
        if (post.getPhotos() != null && post.getPhotos().size() != 0) {
            Photo photo = post.getPhotos().get(0);
            og.setImage(String.format(TechController.URL + "/blog/images/%d/%s", photo.getId(), photo.getFileName()));
        }

        setModelMap(model, og, null, ACTIVE);
        model.addAttribute("categories", Categories.getInstance().list());
        model.addAttribute("post", post);
        model.addAttribute("prev", getPrevPost(post, postsForNav));
        model.addAttribute("next", getNextPost(post, postsForNav));
        model.addAttribute("last", new PostDAOImpl().listForBlog(0, 5));

        return "blog/post";
    }

    @RequestMapping("/blog/ajax/posts/{offset}/{count}")
    public @ResponseBody List<Post> listAjax(
            @PathVariable int offset, @PathVariable int count,
            @RequestParam(value = "category", required = false) String categoryUrl) {

        if (categoryUrl != null) {
            Category category = Categories.getInstance().get(categoryUrl);
            if (category != null) {
                return new PostDAOImpl().listForBlog(offset, count, category);
            } else {
                return new PostDAOImpl().listForBlog(offset, count);
            }
        } else {
            return new PostDAOImpl().listForBlog(offset, count);
        }
    }

    @RequestMapping("/blog/images/{imgId}/{imgFileName}")
    public @ResponseBody byte[] postImageAction(@PathVariable int imgId, @PathVariable String imgFileName) {

        Photo photo = new PhotoDAOImpl().get(imgId);
        if (photo == null) {
            return null;
        }

        return photo.getResource();
    }

    /**
     * Возвращает индекс поста в массиве
     * @param post
     * @param posts
     * @return
     */
    private Integer getPostIndex(Post post, List<Post> posts) {

        for (int i = 0; i < posts.size(); i++) {
            if (post.getId() == posts.get(i).getId()) {
                return i;
            }
        }

        return null;
    }

    /**
     * Возвращает предыдущий относительно указанного пост
     * @param post
     * @param posts
     * @return
     */
    private Post getPrevPost(Post post, List<Post> posts) {

        Integer index = getPostIndex(post, posts);
        if (index == null || index == posts.size() - 1) {
            // нет предыдущего поста
            return null;
        }

        return posts.get(index + 1);
    }

    /**
     * Возвращает следующий пост относительно указанного
     * @param post
     * @param posts
     * @return
     */
    private Post getNextPost(Post post, List<Post> posts) {

        Integer index = getPostIndex(post, posts);
        if (index == null || index == 0) {
            // нет следующего поста
            return null;
        }

        return posts.get(index - 1);
    }
}

site/src/main/java/ru/dom24x7/site/ProfiController.java
package ru.dom24x7.site;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Created by timur on 12.03.17.
 * Контроллер для работы с партнеркой ПРОФИ.РУ
 */
@Controller
public class ProfiController extends BaseController {

    private static final String ACTIVE = "profi";

    @RequestMapping("/profi")
    public String listAction(ModelMap model) {

        setModelMap(model, "Мастера по ремонту", ACTIVE);

        return "profi/list";
    }
}

site/src/main/java/ru/dom24x7/site/SiteController.java
package ru.dom24x7.site;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import ru.dom24x7.component.OpenGraph;
import ru.dom24x7.model.company.dao.CompanyDAOImpl;
import ru.dom24x7.model.photo.Photo;
import ru.dom24x7.model.post.dao.PostDAOImpl;
import ru.dom24x7.model.user.dao.UserDAOImpl;
import ru.dom24x7.site.ajax.response.Response;
import ru.dom24x7.utils.Email;
import ru.dom24x7.utils.StrUtils;

/**
 * Created by timur on 20.09.16.
 *
 * Контроллер для обработки основных страниц, которые доступны без авторизации
 */
@Controller
public class SiteController extends BaseController {

    @RequestMapping("/")
    public String indexAction(ModelMap model) {

        OpenGraph og = new OpenGraph();
        og.setTitle("Сервис учета коммунальных услуг");
        og.setDescription("Сервис учета показаний коммунальных счетчиков, новости и советы из мира ЖКХ, взаимодействие с ТСЖ и УК");
        og.setType(OpenGraph.OG_TYPE_WEBSITE);
        og.setUrl(TechController.URL);
        og.setImage(TechController.URL + "/resources/images/dom24x7.png");

        setModelMap(model, og, "ЖКХ, коммунальный сервис, ТСЖ, УК, коммунальные платежи", null);
        model.addAttribute("usersCount", new UserDAOImpl().count(null));
        model.addAttribute("companiesCount", new CompanyDAOImpl().count((String) null));
        model.addAttribute("posts", new PostDAOImpl().listForBlog(0, 10));

        return "site/index";
    }

    @RequestMapping("/tariffs")
    public String tariffsAction(ModelMap model) {

        setModelMap(model, "Расчет тарифов ЖКХ", "tariffs");
        return "site/tariffs";
    }

    @RequestMapping("/about")
    public String aboutAction(ModelMap model) {

        setModelMap(model, "О проекте");

        return "site/about";
    }

    @RequestMapping("/about/tech")
    public String techAction(ModelMap model) {

        setModelMap(model, "API для работы с сервисом");

        return "site/about/tech";
    }

    @RequestMapping("/about/privacy")
    public String privacyAction(ModelMap model) {

        setModelMap(model, "Политика конфиденциальности");

        return "site/about/privacy";
    }

    @RequestMapping("/about/privacy/terms")
    public String privacyTermsAction(ModelMap model) {

        setModelMap(model, "Политика конфиденциальности. Основные понятия");

        return "site/about/privacy/terms";
    }

    @RequestMapping("/faq")
    public String faqAction(ModelMap model) {

        setModelMap(model, "Часто задаваемые вопросы");

        return "site/faq";
    }

    @RequestMapping("/terms")
    public String termsAction(ModelMap model) {

        setModelMap(model, "Словарь");

        return "site/terms";
    }

    @RequestMapping("/404")
    public String error404Action(ModelMap model) {

        setModelMap(model, "404 Ресурс не найден");

        return "error/404";
    }

    @RequestMapping("/500")
    public String error500Action(ModelMap model) {

        setModelMap(model, "500 Ошибка");

        return "error/500";
    }

    @RequestMapping(value = "/about/feedback", method = RequestMethod.POST)
    public @ResponseBody Response feedbackAjax(
            @RequestParam(value = "name") String name,
            @RequestParam(value = "email") String email,
            @RequestParam(value = "message") String message) {

        String emailMessage = String.format("Имя: %s<br />Обратный адрес: %s<br /><br />%s", name, email, message);
        String userEmailMessage = String.format("Здравствуйте. Спасибо за ваше сообщение. Мы обязательно его прочитаем и " +
                "ответим!<br />Вы нам написали:<br />%s", message);

        Email emailSender = new Email("noanswer@dom24x7.ru", "Tck89mta7s3z");
        // отправляем администратору
        emailSender.send("Сообщение от посетителя сайта dom24x7.ru", emailMessage, "info@dom24x7.ru");
        // отправляем копию пользователю
        emailSender.send("Вы написали службе поддержики сайта dom24x7.ru", userEmailMessage, email);

        return new Response(0, "OK");
    }
}

site/src/main/java/ru/dom24x7/site/admin/AdminAddressController.java
package ru.dom24x7.site.admin;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import ru.dom24x7.component.TableData;
import ru.dom24x7.model.address.Address;
import ru.dom24x7.model.address.dao.AddressDAOImpl;
import ru.dom24x7.site.BaseController;

import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by timur on 16.02.17.
 *
 * Административная панель: управление адресами
 */
@Controller
public class AdminAddressController extends BaseController {

    @RequestMapping("/admin/addresses")
    public String listAction(ModelMap model) {

        setModelMap(model, "Список адресов");

        return "admin/address/list";
    }

    @RequestMapping("/admin/ajax/addresses/list")
    public @ResponseBody TableData listUsersAjax(HttpServletRequest request) {

        int draw = Integer.parseInt(request.getParameter("draw"));
        int start = Integer.parseInt(request.getParameter("start"));
        int length = Integer.parseInt(request.getParameter("length"));
        String search = request.getParameter("search[value]");

        int count = new AddressDAOImpl().count(search);
        List<Address> addresses = new AddressDAOImpl().list(start, length, search);

        if (addresses == null) {
            addresses = new ArrayList<>();
        }

        // загружаем данные по пользователям

        TableData tableData = new TableData();
        tableData.setDraw(draw);
        tableData.setRecordsTotal(count);
        tableData.setRecordsFiltered(count);
        tableData.setData(addresses);

        return tableData;
    }
}

site/src/main/webapp/WEB-INF/views/site/blog/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<c:if test="${category != null}">
    <h1>${category.name}</h1>
    <hr />
</c:if>

<div id="posts" class="row masonry" data-columns></div>
<div id="more-posts"></div>

<script type="text/html" id="tmpl-post-without-photo">
    <div class="item">
        <div class="hpanel blog-box">
            <div class="panel-heading">
                <div class="media clearfix">
                    <a class="pull-left">
                        <img src="/resources/images/logo128x128.png" alt="Dom24x7">
                    </a>
                    <div class="media-body text-right">
                        <small class="text-muted">{{=it.published}}</small><br />
                        <small class="text-muted">{{=it.category}}</small>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <a href="{{=it.url}}"><h4>{{=it.title}}</h4></a>
                {{=it.text}}{{=it.more}}
            </div>
            <div class="panel-footer">
                <i class="fa fa-eye"></i> {{=it.views}} просмотров
            </div>
        </div>
    </div>
</script>
<script type="text/html" id="tmpl-post-with-photo">
    <div class="item">
        <div class="hpanel blog-box">
            <div class="panel-heading">
                <div class="media clearfix">
                    <a class="pull-left">
                        <img src="/resources/images/logo128x128.png" alt="Dom24x7">
                    </a>
                    <div class="media-body text-right">
                        <small class="text-muted">{{=it.published}}</small><br />
                        <small class="text-muted">{{=it.category}}</small>
                    </div>
                </div>
            </div>
            <div class="panel-image">
                <img class="img-responsive" src="/blog/images/{{=it.photo.id}}/{{=it.photo.fileName}}" alt="">
                <div class="title">
                    <a href="{{=it.url}}"><h4>{{=it.title}}</h4></a>
                </div>
            </div>
            <div class="panel-body">{{=it.text}}{{=it.more}}</div>
            <div class="panel-footer">
                <i class="fa fa-eye"></i> {{=it.views}} просмотров
            </div>
        </div>
    </div>
</script>
<script type="text/html" id="tmpl-post-only-photo">
    <div class="item">
        <div class="hpanel blog-box">
            <div class="panel-heading">
                <div class="media clearfix">
                    <a class="pull-left">
                        <img src="/resources/images/logo128x128.png" alt="Dom24x7">
                    </a>
                    <div class="media-body text-right">
                        <small class="text-muted">{{=it.published}}</small><br />
                        <small class="text-muted">{{=it.category}}</small>
                    </div>
                </div>
            </div>
            <div class="panel-image">
                <img class="img-responsive" src="/blog/images/{{=it.photo.id}}/{{=it.photo.fileName}}" alt="">
                <div class="title">
                    <a href="{{=it.url}}"><h4>{{=it.title}}</h4></a>
                </div>
            </div>
            <div class="panel-footer">
                <i class="fa fa-eye"></i> {{=it.views}} просмотров
            </div>
        </div>
    </div>
</script>

<script src="/resources/lib/salvattore/salvattore.min.js"></script>

<script>
    $(document).ready(function () {
        var offset = 0;
        var count = 10;
        var more = false;

        loadPosts(offset, count);

        $(document).scroll(function () {
            if (isScrolledIntoView($('#more-posts'))) {
                if (more) {
                    more = false;
                    offset += count;
                    loadPosts(offset, count);
                }
            } else {
                more = true;
            }
        });

        /**
         * Загрузка порции постов
         * @param offset
         * @param count
         */
        function loadPosts(offset, count) {
            var data = {};
            <c:if test="${category != null}">data.category = '${category.urlName}';</c:if>

            $.post('/blog/ajax/posts/' + offset + '/' + count, data, function (list) {
                if (!list || list.length == 0) {
                    return;
                }

                var grid = document.querySelector('#posts');

                for (var i = 0; i < list.length; i++) {
                    var post = list[i];

                    var texts = post.text == null ? [''] : post.text.split('<hr>');
                    var url = '/blog/post/' + post.id + '/' + post.translitUrl;
                    var more = '';
                    if (texts.length > 1) {
                        // имеется разделитель и нужно показать ссылку на полную версию поста
                        more = '<a href="' + url + '" class="btn btn-primary btn-xs">читать</a>';
                    }

                    var data = {
                        id: post.id,
                        published: '',
                        category: post.category.name,
                        title: '',
                        text: texts[0],
                        views: post.views,
                        more: more,
                        photo: {
                            id: '',
                            fileName: ''
                        },
                        url: url
                    };
                    if (post.publishedDt) {
                        // указана дата и время публикации
                        data.published = moment(post.publishedDt).format('DD.MM.YYYY HH:mm');
                    } else {
                        // отображаем дату и время создания
                        data.published = moment(post.createDt).format('DD.MM.YYYY HH:mm');
                    }
                    if (post.title) {
                        data.title = post.title;
                    }

                    var tmpl = doT.template($('#tmpl-post-without-photo').html());

                    if (post.photos.length != 0) {
                        var photo = post.photos[0];
                        data.photo = photo;
                        if (!post.text) {
                            tmpl = doT.template($('#tmpl-post-only-photo').html());
                        } else {
                            tmpl = doT.template($('#tmpl-post-with-photo').html());
                        }
                    }

                    var item = document.createElement('div');
                    salvattore.appendElements(grid, [item]);

                    item.outerHTML = tmpl(data);
                }
            });
        }

        /**
         * Проверяет, что элемент виден на экране или нет после скролла
         * @param elem
         * @returns {boolean}
         */
        function isScrolledIntoView(elem) {
            var docViewTop = $(window).scrollTop();
            var docViewBottom = docViewTop + $(window).height();

            var elemTop = $(elem).offset().top;
            var elemBottom = elemTop + $(elem).height();

            return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
        }
    });
</script>

site/src/main/webapp/WEB-INF/views/site/blog/post.jsp
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="row">
    <div class="col-md-9">
        <div class="hpanel blog-article-box">
            <div class="panel-heading">
                <h4>${title}</h4>
                <div class="text-muted small">
                    Опубликован: <fmt:formatDate value="${post.publishedDt}" pattern="dd.MM.yyyy HH:mm"/><br />
                    Категория: ${post.category.name}
                </div>
                <br /><br />
                <div class="ya-share2" data-services="collections,vkontakte,facebook,odnoklassniki,moimir,gplus" data-counter=""></div>

            </div>
            <div class="panel-body">
                ${post.text}

                <c:if test="${post.category.id == 4 && post.photos != null && post.photos.size() != 0}">
                    <c:if test="${post.text != null && post.text.trim().length() != 0}"><br /><br /></c:if>
                    <img src="/blog/images/${post.photos.get(0).id}/${post.photos.get(0).fileName}" alt="${post.showTitle}" style="max-width: 100%;">
                    <br />
                </c:if>

                <c:if test="${post.source != null && post.source.length() != 0}">
                    <br />
                    <p>Источник: <a href="${post.source}">${post.source}</a></p>
                </c:if>

                <br /><br />
                <div class="row">
                    <div class="col-xs-6">
                        <c:if test="${next != null}">
                            <a href="/blog/post/${next.id}/${next.translitUrl}"><i class="fa fa-long-arrow-left"></i> вперед</a>&nbsp;&nbsp;&nbsp;
                        </c:if>
                        <c:if test="${prev != null}">
                            <a href="/blog/post/${prev.id}/${prev.translitUrl}">назад <i class="fa fa-long-arrow-right"></i></a>
                        </c:if>
                    </div>
                    <div class="col-xs-6 text-right">
                        <div class="ya-share2" data-services="collections,vkontakte,facebook,odnoklassniki,moimir,gplus" data-counter=""></div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <i class="fa fa-eye"></i> ${post.views} просмотров
            </div>
        </div>
        <c:if test="${post.photos != null && post.photos.size() != 0}">
            <c:if test="${post.category.id != 4 || post.photos.size() > 1}">
                <link rel="stylesheet" href="/resources/themes/homer/vendor/blueimp-gallery/css/blueimp-gallery.min.css" />

                <style>
                    .lightBoxGallery {
                        text-align: center;
                    }
                    .lightBoxGallery a {
                        margin: 5px;
                        display: inline-block;
                    }
                </style>

                <div class="hpanel">
                    <div class="panel-body">
                        <div class="lightBoxGallery">
                            <c:forEach items="${post.photos}" var="photo">
                                <a href="/blog/images/${photo.id}/${photo.fileName}" title="${post.showTitle}" data-gallery=""><img src="/blog/images/${photo.id}/${photo.fileName}" style="max-width: 240px; max-height: 160px"></a>
                            </c:forEach>
                        </div>
                    </div>
                </div>

                <div id="blueimp-gallery" class="blueimp-gallery">
                    <div class="slides"></div>
                    <h3 class="title"></h3>
                    <a class="prev">‹</a>
                    <a class="next">›</a>
                    <a class="close">×</a>
                    <a class="play-pause"></a>
                    <ol class="indicator"></ol>
                </div>

                <script src="/resources/themes/homer/vendor/blueimp-gallery/js/jquery.blueimp-gallery.min.js"></script>
            </c:if>
        </c:if>
        <div class="hpanel">
            <div class="panel-body">
                еще по теме:
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="hpanel">
            <div class="panel-body">
                <p>последние посты:</p>
                <c:if test="${last != null && last.size() != 0}">
                    <ul>
                        <c:forEach items="${last}" var="lastPost">
                            <li><a href="/blog/post/${lastPost.id}/${lastPost.translitUrl}">${lastPost.showTitle}</a></li>
                        </c:forEach>
                    </ul>
                </c:if>
            </div>
        </div>
        <div class="hpanel">
            <div class="panel-body">
                <p>категории:</p>
                <c:if test="${categories != null && categories.size() != 0}">
                    <ul>
                        <c:forEach items="${categories}" var="category">
                            <li><a href="/blog/${category.urlName}">${category.name}</a></li>
                        </c:forEach>
                    </ul>
                </c:if>
            </div>
        </div>
    </div>
</div>

<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
<script src="//yastatic.net/share2/share.js"></script>